[charts/gateway]: Update 10.1.00_CR2 tag to 11.0.00
CAAPIM/apim-charts pull request #193
Opened 2023-01-31 02:35 UTC by jennarddy

**Description of the change**

Update Gateway image version from 10.1.00_CR2 to 11.0.00

**Benefits**

Enable usage of latest release of Layer 7 Gateway

**Drawbacks**

None. It's a straightforward version update. The image already exists on Docker Hub.

**Applicable issues**

  - fixes #

**Additional information**
Verified on GKE using local copy of fork:
```
PS C:\Users\jd683606.BRCMLTD\work\github\CAAPIM\apim-charts-jennarddy\charts> helm install jd683606-ssg-11 --set-file "license.value=LICENSE.xml" --set "license.accept=true" gateway
NAME: jd683606-ssg-11
LAST DEPLOYED: Mon Jan 30 18:04:36 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
##################################################################################
####                                 Success!                                 ####
##################################################################################
####                 Your gateway deployment has been INSTALLED               ####
##################################################################################

To view the Gateway's services you can use the following command
$ kubectl get svc -n default | grep gateway

To learn more about the Gateway Helm Chart check out the following links

Gateway Helm Chart Readme
- https://github.com/CAAPIM/apim-charts/tree/stable/charts/gateway

Thinking in Kubernetes
- https://techdocs.broadcom.com/us/en/ca-enterprise-software/layer7-api-management/api-gateway/congw-10-1/learning-center/thinking-in-kubernetes.html#thinkingk8s

PS C:\Users\jd683606.BRCMLTD\work\github\CAAPIM\apim-charts-jennarddy\charts> kubectl get svc -n default
jd683606-ssg-11-gateway                   LoadBalancer   240.129.245.154   10.210.128.136   8443:32660/TCP                                  3m5s
jd683606-ssg-11-gateway-management        LoadBalancer   240.129.244.73    10.210.128.172   9443:31896/TCP                                  3m5s
jd683606-ssg-11-mysql                     ClusterIP      240.129.246.197   <none>           3306/TCP                                        3m5s
jd683606-ssg-11-mysql-headless            ClusterIP      None              <none>           3306/TCP                                        3m5s
```

Logged on to Policy Manager using 10.210.128.172:9443
![image](https://user-images.githubusercontent.com/25108787/215648125-431fbba7-df70-4c92-a0d0-0330b44c7430.png)

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[charts/gateway]`)
- [X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

2023-01-31 02:36 UTC, jennarddy commented on charts/gateway/values.yaml
> +      cloud.google.com/load-balancer-type: "Internal"
I forgot to comment this back

2023-01-31 02:36 UTC, jennarddy commented on charts/gateway/values.yaml
> +    cloud.google.com/load-balancer-type: "Internal"
Uncommented during GKE testing. I forgot to comment this back.

2023-01-31 02:47 UTC, jennarddy commented on charts/gateway/values.yaml
> +      cloud.google.com/load-balancer-type: "Internal"
Resolved by https://github.com/CAAPIM/apim-charts/pull/193/commits/32daaae94b8d7f0ffc7f9d15b56c23e82e7e7ace

2023-01-31 02:47 UTC, jennarddy commented on charts/gateway/values.yaml
> +    cloud.google.com/load-balancer-type: "Internal"
Resolved by https://github.com/CAAPIM/apim-charts/pull/193/commits/32daaae94b8d7f0ffc7f9d15b56c23e82e7e7ace

2023-01-31 04:24 UTC, Gazza7205 requested changes
Thanks, the updates look good -

Could you add a 3.0.5 updates section (above 3.0.2) and reference the release notes - specifically that the upgrade procedure requires careful planning given the embedded Hazelcast update requires Gateway deployments to be scaled to 0.

https://techdocs.broadcom.com/us/en/ca-enterprise-software/layer7-api-management/api-gateway/congw-11-0/release-notes_cgw.html

2023-01-31 04:32 UTC, APIM-KiranVaddadi reviewed
LGTM. Changed the readme file to fix typo.

2023-01-31 21:58 UTC, jennarddy commented
> Thanks, the updates look good -
> 
> Could you add a 3.0.5 updates section (above 3.0.2) and reference the release notes - specifically that the upgrade procedure requires careful planning given the embedded Hazelcast update requires Gateway deployments to be scaled to 0.
> 
> https://techdocs.broadcom.com/us/en/ca-enterprise-software/layer7-api-management/api-gateway/congw-11-0/release-notes_cgw.html

I've added 3.0.5 General Updates section. Please take a look. Thanks.

2023-02-01 04:55 UTC, jennarddy commented on charts/gateway/README.md
> +***The default image tag in values.yaml and production-values.yaml now points at specific GA or CR versions of the API Gateway. The appVersion in Chart.yaml has also be updated to reflect that. As of
I'll revert the version here, now that the 3.0.5 section is added

2023-02-01 04:55 UTC, jennarddy commented on charts/gateway/README.md
> +***The default image tag in values.yaml and production-values.yaml now points at specific GA or CR versions of the API Gateway. The appVersion in Chart.yaml has also be updated to reflect that. As of
Will also fix a typo I see

2023-02-01 04:58 UTC, jennarddy commented on charts/gateway/README.md
> +***The default image tag in values.yaml and production-values.yaml now points at specific GA or CR versions of the API Gateway. The appVersion in Chart.yaml has also be updated to reflect that. As of
Addressed by https://github.com/CAAPIM/apim-charts/pull/193/commits/c45d1c4c1d18e92bc0d2039252b5e6ca1f4ca2a3

2023-02-01 07:45 UTC, gvermeulen7205 approved these changes

2023-02-01 07:46 UTC, Gazza7205 approved these changes

2023-02-01 07:50 UTC, merged