Updated MySQL version in Readme
CAAPIM/apim-charts pull request #41
Opened 2021-03-02 10:00 UTC by as666499

**Description of the change**

**Benefits**

**Drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [] Variables are documented in the README.md
- [] Title of the PR starts with chart name (e.g. `[charts/gateway]`)
- [] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

2021-03-02 12:19 UTC, APIM-KiranVaddadi requested changes

2021-03-02 12:19 UTC, APIM-KiranVaddadi commented on charts/portal/README.md
> +- A dedicated MySQL 8.22 server [TechDocs](https://techdocs.broadcom.com/us/en/ca-enterprise-software/layer7-api-management/api-developer-portal/5-0/install-configure-and-upgrade/install-portal-on-do
We support both 5.6/7 and 8.22

2021-03-02 12:19 UTC, APIM-KiranVaddadi commented on charts/portal/values-production.yaml
> +  # podSecurityContext:
podSecurity is under primary
https://github.com/bitnami/charts/blob/master/bitnami/mysql/values.yaml

2021-03-02 12:19 UTC, APIM-KiranVaddadi commented on charts/portal/values.yaml
> +  # podSecurityContext:
Same as above.

2021-03-02 12:20 UTC, APIM-KiranVaddadi requested changes

2021-03-02 12:20 UTC, APIM-KiranVaddadi commented on charts/portal/README.md
> -- A dedicated MySQL 5.6/7 server [TechDocs](https://techdocs.broadcom.com/us/en/ca-enterprise-software/layer7-api-management/api-developer-portal/5-0/install-configure-and-upgrade/install-portal-on-d
Tech docs need to point to 5.0CR1

2021-03-03 09:31 UTC, APIM-KiranVaddadi reviewed
LGM

2021-03-03 09:32 UTC, APIM-KiranVaddadi approved these changes

2021-03-03 09:44 UTC, Gazza7205 approved these changes

2021-03-03 11:58 UTC, merged