[charts/portal]:APIVersion for ingress-resources of Portal
CAAPIM/apim-charts pull request #64
Opened 2021-05-13 17:07 UTC by ksaladi

**Description of the change**
API version change from v1beta1 to v1 for ingress-resources of Portal. "v1beta1" is deprecated in 1.16 and expected in version is "v1"

Allows to use latest API version supported in K8s cluster.

**Benefits**
- Avoids warning while installing the helm charts.

**Drawbacks**

**Applicable issues**

  - fixes #
  

**Additional information**

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[charts/gateway]`)

2021-05-13 20:24 UTC, Gazza7205 requested changes
Please check backwards compatibilty with our current support matrix - networking/v1 may not be present in some of the versions we evaluate against. This also needs to be compatible with the version of Nginx that's used.

2021-05-14 08:49 UTC, ksaladi commented
> Please check backwards compatibilty with our current support matrix - networking/v1 may not be present in some of the versions we evaluate against. This also needs to be compatible with the version of Nginx that's used.

@Gazza7205 Our claim for K8s support for  Portal 5.0.2 would be 1.19+  and the "networking.k8s.io/v1" is supported from 1.19 (https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class) and the expectation is that  Nginx-ingress-controller should support the K8s 1.19+ version.

2021-05-14 09:13 UTC, Gazza7205 commented
> > Please check backwards compatibilty with our current support matrix - networking/v1 may not be present in some of the versions we evaluate against. This also needs to be compatible with the version of Nginx that's used.
> 
> @Gazza7205 Our claim for K8s support for Portal 5.0.2 would be 1.19+ and the "networking.k8s.io/v1" is supported from 1.19 (https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class) and the expectation is that Nginx-ingress-controller should support the K8s 1.19+ version.

I understand, that still introduces a breaking change for anyone on less than 1.19. We can account for both using semverCompare.

2021-05-14 17:28 UTC, ksaladi commented
> > > Please check backwards compatibilty with our current support matrix - networking/v1 may not be present in some of the versions we evaluate against. This also needs to be compatible with the version of Nginx that's used.
> > 
> > 
> > @Gazza7205 Our claim for K8s support for Portal 5.0.2 would be 1.19+ and the "networking.k8s.io/v1" is supported from 1.19 (https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class) and the expectation is that Nginx-ingress-controller should support the K8s 1.19+ version.
> 
> I understand, that still introduces a breaking change for anyone on less than 1.19. We can account for both using semverCompare.

@Gazza7205 changes updated to support backward compatibility

2021-05-17 08:26 UTC, Gazza7205 reviewed
@ksaladi - looks good to me, has this been tested?

2021-05-18 08:55 UTC, ksaladi commented
> @ksaladi - looks good to me, has this been tested?

@Gazza7205 Tested.
**Details:-**
- Rancher k8s version 1.17 and 1.20
- Also verified ingress-resources with the ingress-controller that are coming from our charts in Azure K8s.

2021-05-18 09:12 UTC, APIM-KiranVaddadi approved these changes
LGTM

2021-05-18 09:18 UTC, Gazza7205 approved these changes

2021-05-18 09:34 UTC, merged